name: Deploy Firebase Functions

on:
  push:
    branches:
      - main # Branch where github action gets triggered

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Match this version to the version in functions/package.json
          cache: 'yarn'

      - name: Install Firebase CLI
        run: yarn global add firebase-tools

      - name: Install dependencies
        run: yarn
        working-directory: ./apps/functions

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only functions
